Add banner to calculator, with 2019 and 2020 presets
Recidiviz/supervision-success-component pull request #112
Opened 2021-09-02 12:36 UTC by nasaownsky

## Description of the change

Added banner to calculator, with 2019 and 2020 presets

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #108 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-02 16:35 UTC, jessex requested changes
This looks and functions great, @nasaownsky! Just two small comments for you.

Also, in local testing, I found that the banner text bleeds over the right side in very thing displays. For example, if you choose the Galaxy Fold mobile device layout in Chrome Dev Tools, you can see this:
<img width="1904" alt="Screen Shot 2021-09-02 at 10 31 18 AM" src="https://user-images.githubusercontent.com/431895/131882691-0ec2e9b0-8b48-4a74-bb98-36e8bdc166de.png">

2021-09-02 16:35 UTC, jessex commented on src/SupervisionSuccess/SupervisionSuccessContainer.js
> +    setChangeInRevocations(-21);
Let's extract these out to constants named `2020_CHANGE_IN_REVOCATIONS` and `2020_CHANGE_IN_NEW_ADMISSIONS`

2021-09-02 16:35 UTC, jessex commented on src/SupervisionSuccess/components/Banner/Banner.js
> +            disabled={changeInRevocations === -21 && changeInNewAdmissions === -14}
We would reference those same constants I requested in the other comment here, instead of these magical numbers.

2021-09-03 09:15 UTC, nasaownsky commented
@jessex Fixes there they go!

2021-09-03 16:39 UTC, jessex approved these changes
Good to go! Well done, @nasaownsky! We made it just in time.

2021-09-03 16:40 UTC, merged