bootstrapped react, test and lint
Recidiviz/supervision-success-component pull request #12
Opened 2020-09-11 13:06 UTC by Wmaileq

## Description of the change

- bootstrapped CRA
- added linters
- added test util settings and sample test
- added first component

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1, #2 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-11 17:28 UTC, jessex requested changes
Code looks good, thanks @Wmaileq! Heads up, though, `yarn test` and `yarn lint` both fail for me with a completely fresh install. Do you see the same failures?
```
$ yarn test
 FAIL  src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js
  ● Test suite failed to run

    Cannot find module '../providers/SupervisionSuccessModelProvider' from 'SupervisionSuccess.test.js'

       5 | import SupervisionSuccessModelProvider from "../providers/SupervisionSuccessModelProvider";
       6 | 
    >  7 | jest.mock("../providers/SupervisionSuccessModelProvider", () => ({
         |      ^
       8 |   SupervisionSuccessModelProvider: jest.fn().mockReturnValue(null),
       9 | }));
      10 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js:7:6)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.429s
Ran all test suites.

Watch Usage: Press w to show more.

$ yarn lint
yarn run v1.22.4
$ eslint ./src

/Users/clementinejacoby/Documents/projects/supervision-success-component/src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js
  5:45  error  Unable to resolve path to module '../providers/SupervisionSuccessModelProvider'  import/no-unresolved
  5:45  error  Missing file extension for "../providers/SupervisionSuccessModelProvider"        import/extensions

✖ 2 problems (2 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2020-09-11 17:28 UTC, jessex commented on package.json
> +  "name": "supervision-success-component",
A few more bits of metadata to add in here:
```
{
  ...
  "description": "A tool for modeling the impact of an increase in supervision success on the broader justice system",
  "repository": "git@github.com:Recidiviz/supervision-success-component.git",
  "author": "Recidiviz <team@recidiviz.org>",
  "license": "GNU General Public License v3",
  ...
}
```

2020-09-14 15:57 UTC, Wmaileq commented
> Code looks good, thanks @Wmaileq! Heads up, though, `yarn test` and `yarn lint` both fail for me with a completely fresh install. Do you see the same failures?
> 
> ```
> $ yarn test
>  FAIL  src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js
>   ● Test suite failed to run
> 
>     Cannot find module '../providers/SupervisionSuccessModelProvider' from 'SupervisionSuccess.test.js'
> 
>        5 | import SupervisionSuccessModelProvider from "../providers/SupervisionSuccessModelProvider";
>        6 | 
>     >  7 | jest.mock("../providers/SupervisionSuccessModelProvider", () => ({
>          |      ^
>        8 |   SupervisionSuccessModelProvider: jest.fn().mockReturnValue(null),
>        9 | }));
>       10 | 
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
>       at Object.<anonymous> (src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js:7:6)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        1.429s
> Ran all test suites.
> 
> Watch Usage: Press w to show more.
> 
> $ yarn lint
> yarn run v1.22.4
> $ eslint ./src
> 
> /Users/clementinejacoby/Documents/projects/supervision-success-component/src/SupervisionSuccess/__tests__/SupervisionSuccess.test.js
>   5:45  error  Unable to resolve path to module '../providers/SupervisionSuccessModelProvider'  import/no-unresolved
>   5:45  error  Missing file extension for "../providers/SupervisionSuccessModelProvider"        import/extensions
> 
> ✖ 2 problems (2 errors, 0 warnings)
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

fixed

2020-09-14 21:54 UTC, jessex approved these changes
Good to go! 🚀

2020-09-14 21:54 UTC, merged