wadded header and methodology
Recidiviz/supervision-success-component pull request #28
Opened 2020-09-22 12:30 UTC by Wmaileq

## Description of the change

- added header and methodology text
- refactored css to scss (to have better developer experience while development of mobile mock up)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #8 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-22 19:02 UTC, jessex commented
Note, @Wmaileq, that I changed you PR description to _not_ close #8, since the copy is still not finalized. For example, there is still "Lorem ipsum" text at the top.

Also, make sure to resolve the new merge conflicts when you get a chance.

2020-09-22 19:10 UTC, jessex requested changes
Looking good so far, @Wmaileq! No comments on the code. Thanks for the switch to SCSS in the component styling.

One UI thing I notice is that the background color in the bottom section is currently white, but it's a light grey in the mocks. Reminder that Juan Agron added links to assets, fonts, colors, etc. in a comment on September 17th that is attached to the mocks in the PRD. We should make sure we're matching those--I think we're pretty good, and that lower background color is the only thing I've noticed that's off so far, but it's worth double-checking.

2020-09-22 19:10 UTC, jessex commented on src/SupervisionSuccess/SupervisionSuccess.js
> +  the total operating budget of thos facilities is saved. For remaining population differentials-namely
Typo: thos -> those

2020-09-23 08:45 UTC, Wmaileq commented
Actually i don't think that the header text and the methodology text should be in-scope of the component.
Maybe I should take this components out of SupervisionSuccess component and reproduce them in App.js just to show an example how it could be realized on final page?

2020-09-23 16:47 UTC, jessex commented
[Right here, Vlad](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?disco=AAAAG81Tf7o)

2020-09-23 16:53 UTC, jessex approved these changes
Looks good, @Wmaileq, thanks! I'm going to merge this PR. But take a look at that linked comment tomorrow and if you see anything that we're not yet matching, then let's file a follow-up PR to match it.

2020-09-23 16:53 UTC, merged

2020-09-24 09:08 UTC, Wmaileq commented
> [Right here, Vlad](https://docs.google.com/document/d/1vssQ4JB8VyfInFpdw7F_4laQG0WVXYv6u4FwIpIFUoQ/edit?disco=AAAAG81Tf7o). Just follow whatever is linked in that comment.

Looks like i have no access to comments.

2020-09-24 19:09 UTC, jessex commented
Sorry about that, Vlad! Just sent you an email. We can continue the conversation there.