accessibility attempt
Recidiviz/supervision-success-component pull request #34
Opened 2020-09-24 14:43 UTC by Wmaileq

## Description of the change

Looked through component - all controls(selects and slider) are accessible.
Tried to impress what is shown on the graph, maybe you have thoughts about it?

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-24 16:58 UTC, jessex requested changes
A few nits on the aria-label for the chart, but I think that looks great. However, poking around the Accessibility tab in the Chrome Dev Tools, it's not obvious to me that all of the components have alt text, and I don't see other aria-labels in the codebase. How do you know those components are accessible as-is?

2020-09-24 16:58 UTC, jessex commented on src/SupervisionSuccess/utils/transformChartAsText.js
> +  if (dataset[12]) result += `After 1st year: ${dataset[12]}`;
Need a space before the start of this one: ` After...`

2020-09-24 16:58 UTC, jessex commented on src/SupervisionSuccess/utils/transformChartAsText.js
> +  if (dataset[36]) result += ` After 3rd year: ${dataset[36]}`;
Need a period at the end of this one.

2020-09-24 16:58 UTC, jessex commented on src/SupervisionSuccess/utils/transformChartAsText.js
> +  if (dataset[48]) result += ` After 4th year: ${dataset[48]}`;
Need a period at the end of this one.

2020-09-24 16:58 UTC, jessex commented on src/SupervisionSuccess/utils/transformChartAsText.js
> +  if (dataset[60]) result += ` After 5th year: ${dataset[60]}`;
Need a period at the end of this one.

2020-09-24 20:08 UTC, Wmaileq commented
> A few nits on the aria-label for the chart, but I think that looks great. However, poking around the Accessibility tab in the Chrome Dev Tools, it's not obvious to me that all of the components have alt text, and I don't see other aria-labels in the codebase. How do you know those components are accessible as-is?

I just tested it with screen reader emulator. Cmd + f5 on Mac.
The problem is if this components are not accessible we will need to find alternatives or build our custom components.
But, luckily slider and selects functions well

2020-09-24 21:53 UTC, jessex commented
Thanks for the explanation, @Wmaileq! Once the comments are resolved, I think we're good here.

2020-09-25 17:57 UTC, jessex approved these changes
Good to go! 🚀

2020-09-25 17:58 UTC, merged