Several updates
Recidiviz/supervision-success-component pull request #84
Opened 2021-07-22 12:21 UTC by nasaownsky

## Description of the change

1. Minor copy updates for sliders
2. Update impact allocations (% from new admissions, % from revocations) in UI
3. Add formatting for numbers in UI
4. Verify accessibility standards 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #73 , closes #81 , closes #82 , closes #83 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-07-22 20:26 UTC, jessex requested changes
Nice batch, @nasaownsky! A few issues from local testing:

Regarding #73, if you go into Chrome's developer tools and click "Lighthouse" and generate a report, Accessibility is currently getting a 98/100, which is great! But there is one small issue still outstanding that we should fix:
<img width="755" alt="Screen Shot 2021-07-22 at 14 20 50" src="https://user-images.githubusercontent.com/431895/126704664-0003c94c-99db-4279-9cc1-140881883874.png">

Regarding #81, the issue calls out that we want to make sure we don't introduce any decimals into our numbers, but it looks like we did in this PR. Now, if the costs are below $100M, it will add a decimal to keep using 3 digits. We don't want that to happen. The number below should just round off to $82M:
<img width="1317" alt="Screen Shot 2021-07-22 at 14 13 00" src="https://user-images.githubusercontent.com/431895/126704801-f0feb3bc-4acf-4c9c-84ba-78ed536b42d7.png">

Regarding #82, if you look at this in mobile, the new section has some kind of strange padding. It looks further away from the outcomes numbers it corresponds to, and closer to the title of the chart section. We should make it so that it's at least not that close to the chart text:
<img width="210" alt="Screen Shot 2021-07-22 at 14 17 35" src="https://user-images.githubusercontent.com/431895/126704931-c63069cf-19be-4bd6-bf4f-258dc906be1a.png">

Also, @nasaownsky, I noticed in that mobile screenshot that the chart is behaving strangely, like it's cut off horizontally maybe? It's not displaying all of the x-axis values you would expect. Can you look into that? Test it out with different projection length values and make sure you can actually see the entire chart on mobile.

2021-07-22 20:26 UTC, jessex commented on src/SupervisionSuccess/utils/formatNumber.js
> +const formatNumber = (number, isAbsolute = false) => {
Let's add a note about what exactly this changes, i.e. what formatting it does.

2021-07-23 18:08 UTC, nasaownsky commented
@jessex Fixed all you have requested. The issue with chart happens when xAxis ticks don't fit in available space. The data though shows correctly. I can decrease font-size, but on some scales all ticks won't be able to show. This is how chart.js works.

<img width="368" alt="Снимок экрана 2021-07-23 в 21 08 00" src="https://user-images.githubusercontent.com/20225344/126823495-68f42a66-4fa9-4e72-96af-8982bcb66ec7.png">

2021-07-23 18:15 UTC, jessex commented
Thanks for this, @nasaownsky! I can see that getting the x-axis labels perfectly in frame for all possible viewports is a challenge given our current setup. The only unfortunate thing about it at the moment is that when you test out different resolutions/devices, you see that x-axis values will be missing for certain projection lengths. For example, for Pixel 2XL, you see that there are labels missing when projection length is 4 years but not when it's 3. Conversely, for Galaxy S5, the opposite is true, and labels are missing only when projection length is 3. I am going to file a separate ticket to investigate it, but we don't need to block this work on that.

2021-07-23 18:15 UTC, jessex approved these changes
The previously noted issues are all fixed. Good to go on this one!

2021-07-23 18:16 UTC, merged